development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:e60d577b790b65a8adf8fbd20d8a5b47@crestfish.redistogo.com:10934/
  channel_prefix: cars_production
